### ISSUE TITLE
lua/cursor.lua hangs when TERM=dumb

### ISSUE THREAD

**Issue by paride** [martanne/vis-test#15]
Steps to reproduce:
```
$ TERM=dumb ./test.sh cursor.lua
vis v0.5 +curses +lua +tre +acl +selinux
cursor                        
[test hung]
```

**Comment by martanne** [comment]
Can't seem to reproduce here. Can you investigate further i.e. what is it doing/where is it hanging?

**Comment by paride** [comment]
With `TERM=dumb` vis hangs immediately on my system: the problem doesn't depend on the test. Just running `TERM=dumb vis` makes it hang, eating 100% of the cpu.

I'm attaching the exact `dumb` terminfo file that gets read on my system, perhaps you could try to reproduce the issue by placing it in `~/.terminfo/d/dumb`. It's gzipped so GitHub accepts it.

If I set TERM to a random string, vis doesn't hang. The condition is triggered by the usage of the `dumb` terminfo.

[dumb.gz](https://github.com/martanne/vis-test/files/1913019/dumb.gz)

**Comment by paride** [comment]
I can't reproduce this anymore.
