### ISSUE TITLE
sam/commands/unicode-replace fails with LANG=C

### ISSUE THREAD

**Issue by paride** [martanne/vis-test#25]
Error diff:

```
$ make LANG=C
[...]
Running test ./commands/unicode-replace with vis ... FAIL
[...]
Tests ok 27/28
make: *** [Makefile:2: test] Error 1

$ cat commands/unicode-replace.vis.err
--- ./commands/unicode-replace.sam.out  2020-07-07 12:13:42.274738166 +0200
+++ ./commands/unicode-replace.vis.out  2020-07-07 12:13:42.282738109 +0200
@@ -1,5 +1,5 @@
-♫
-♫♫
-♫♫♫
-♫♫
-♫
+♪
+♪♪
+♪♪♪
+♪♪
+♪
```
Running the tests with `make LANG=C.UTF-8` works.

**Comment by martanne** [comment]
The `C.UTF-8` locale isn't in upstream glibc (see also #20), so it would break on different systems.

I suggest to set the environment variable to something suitable for your system.

**Comment by paride** [comment]
If the test result is locale-dependent then the right locale should be set by the test script I think. What about setting `LANG=en_US.UTF-8`?
