### ISSUE TITLE
selections-trim fails

### ISSUE THREAD

**Issue by erf** [martanne/vis-test#26]
In this [pr](https://github.com/martanne/vis/pull/892) i saw the `selections-trim` test fail. 

I tried to type the keys manually and i ended up with this:

```
>1<, 2, >3<
>4<, >5<, >6<
>7<, >8<, >9<
```

Whilst the `.ref` is:

```
>1<, >2<, >3<
>4<, >5<, >6<
>7<, >8<, >9<
```

Is mine the right one? Should i make a PR for the change?

**Comment by martanne** [comment]
Before your changes the test worked, after your changes it failed.

This means your changes don't do what they are supposed to do i.e. they introduced a bug.

Unless of course you wanted to change the behavior. However, then you would need to argue why your proposal is better etc.
